### ISSUE TITLE
安装依赖包报错

### ISSUE THREAD

**Issue by linchuangbin2019** [linuxdeepin/youqu#112]
Traceback (most recent call last):
  File "manage.py", line 106, in <module>
    Manage()
  File "manage.py", line 36, in __init__
    from src.plugins.mng import trim
  File "/home/test/Desktop/my_project/src/__init__.py", line 24, in <module>
    from src.dbus_utils import DbusUtils as DbusUtils
  File "/home/test/Desktop/my_project/src/dbus_utils.py", line 7, in <module>
    import dbus
  File "/home/test/Desktop/my_project/.venv/lib/python3.8/site-packages/dbus/__init__.py", line 71, in <module>
    import dbus.types as types
  File "/home/test/Desktop/my_project/.venv/lib/python3.8/site-packages/dbus/types.py", line 6, in <module>
    from _dbus_bindings import (
ModuleNotFoundError: No module named '_dbus_bindings'

**Comment by mikigo** [comment]
https://youqu.uniontech.com/SIG.html

可能需要提供更多信息才能定位出问题，加群，在群里聊吧
